@startuml

autonumber
actor "Gestor da OrganizaÁ„o" as CO

activate CO

CO -> ":Sistema" : Inicia a especificaÁ„o de colaborador de organizaÁ„o
activate ":Sistema"
":Sistema" --> CO : Solicita os dados necess·rios do colaborador
deactivate ":Sistema"

CO -> ":Sistema" : Fornece os dados solicitados
activate ":Sistema"
":Sistema" --> CO : Apresenta os dados e solicita confirmaÁ„o 
deactivate ":Sistema"

CO -> ":Sistema" : Confirma
activate ":Sistema"
":Sistema" --> CO : OperaÁ„o bem sucedida
deactivate ":Sistema"

deactivate CO

@enduml
